4 TO - DO - Task
Please complete all the problem listed below.
4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:


Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np
empty_array = np.empty((2,2))
one_array = np.ones((4,2))

full_array = np.full((4,4),5)

zeros_array = np.zeros_like(full_array)

ones_array = np.ones_like(full_array)

new_list = [1,2,3,4]
numpy_array = np.array(new_list)

print("empty array: ",empty_array)
print("one array: ",one_array)
print("full array: ",full_array)
print("Zerose array: ",zeros_array)
print("arrays of one: ",ones_array)
print("numpy array: ",numpy_array)


empty array:  [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]
one array:  [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
full array:  [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
Zerose array:  [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
arrays of one:  [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
numpy array:  [1 2 3 4]


4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

array_range = np.arange(10,50)
print("array from 10 to 49 is \n", array_range)


reshape_array = np.arange(9).reshape(3,3)
print("reshape value: \n",reshape_array)

identity_matrix = np.eye(3)
print("identity matrix:\n ",identity_matrix)

random_array = np.random.random(30)
array_mean = random_array.mean()
print("random array size \n",random_array)
print("mean of the array",array_mean)

random_10x10 = np.random.random(10*10)
minimum = random_10x10.min()
maximum = random_10x10.max()


print("The random minimum number is ",minimum)
print("The random maximum number is ",maximum)


zero_array = np.zeros(10)
zero_array[4]=1
print("Zero array with 5th element as 1: ",zero_array)


arr = [1,2,0,0,4,0]
reverse_array = np.array(arr)[::-1]
print("reversed array: ",reverse_array)


array_2d_boreder = np.ones((5,5))
array_2d_boreder[1:-1,1:-1] = 0
print("2d array with 1 on border and 0 inside: \n",array_2d_boreder)

checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1:2] = 1
print("8X8 checkerboard pattern: \n", checkerboard)





array from 10 to 49 is 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
reshape value: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
identity matrix:
  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
random array size 
 [0.26054749 0.14861236 0.19090731 0.3272872  0.28618576 0.40449157
 0.46213145 0.31927232 0.3010486  0.10372057 0.86932334 0.05063974
 0.12144784 0.20954528 0.61435838 0.00226495 0.47162342 0.36080831
 0.16553333 0.05700702 0.47351189 0.43552915 0.26443469 0.34289568
 0.02856959 0.86879857 0.08526927 0.51078096 0.43554133 0.67646829]
mean of the array 0.3282851893591199
The random minimum number is  0.0019157456719920418
The random maximum number is  0.9991583935725328
Zero array with 5th element as 1:  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
reversed array:  [0 4 0 0 2 1]
2d array with 1 on border and 0 inside: 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
8X8 checkerboard pattern: 

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [3]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

addition_xy = x+y
print("The addition of two arrays is \n ",addition_xy)

subtraction_xy = x-y
print("The subtraction of two arrays is \n",subtraction_xy)

multiplication_x = x*3
print("The multiplication of array with integer x \n",multiplication_x)

square_x = np.square(x)
print("Square of each element in x: \n",square_x)


dot_productvw = np.dot(v, w)
dot_productxv = np.dot(x, v)
dot_productxy = np.dot(x, y)

print("Product of v and w: \n",dot_productvw)
print("Product of x and v: \n",dot_productxv)
print("product of x and y: \n",dot_productxy)

concat_xy_row = np.concatenate((x,y), axis = 0)
concat_vw_col = np.concatenate((v,w)).T

print("Concatenate of x and y along rows: \n",concat_xy_row)
print("Concatenate of v and w along columns: \n",concat_vw_col)

try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    concat_xv_error = str(e)

print("Error when concatenating x and v:\n", concat_xv_error)


The addition of two arrays is 
  [[ 6  8]
 [10 13]]
The subtraction of two arrays is 
 [[-4 -4]
 [-4 -3]]
The multiplication of array with integer x 
 [[ 3  6]
 [ 9 15]]
Square of each element in x: 
 [[ 1  4]
 [ 9 25]]
Product of v and w: 
 219
Product of x and v: 
 [29 77]
product of x and y: 
 [[19 22]
 [50 58]]
Concatenate of x and y along rows: 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate of v and w along columns: 
 [ 9 10 11 12]
Error when concatenating x and v:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A^-1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)^T = B^TA^T

In [1]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("A * A^-1 = I:")
print(I)

AB = np.dot(A, B)
BA = np.dot(B, A)
AB_not_equal_BA = not np.array_equal(AB, BA)
print("\nAB != BA:", AB_not_equal_BA)

AB_T = AB.T
BT_AT = np.dot(B.T, A.T)
AB_T_equals_BT_AT = np.array_equal(AB_T, BT_AT)
print("\n(AB)^T = B^T * A^T:", AB_T_equals_BT_AT)


A * A^-1 = I:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB != BA: True

(AB)^T = B^T * A^T: True


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [2]:
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("Solution (x, y, z):", X)


Solution (x, y, z): [ 2.  1. -2.]
